language: rust
cargo: cache
rust:
  - nightly
before_install:
  - rustup target add wasm32-unknown-unknown
  - command -v wasm-build || cargo install pwasm-utils-cli --version 0.6.0 --bin wasm-build
  - ./wasm-install.sh
env:
  - TUTOR_DIR=step-0
  - TUTOR_DIR=step-1
  - TUTOR_DIR=step-2
  - TUTOR_DIR=step-3
  - TUTOR_DIR=step-4
  - TUTOR_DIR=step-5
script:
  - cd $TUTOR_DIR
  - ./build.sh
  - ../wasm-install/bin/wasm-validate target/pwasm_tutorial_contract.wasm
